<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">NeighbApp</a>
        </div>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
                <li><a href="#">Metrics</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Push <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Push ALL</a></li>
                        <li><a href="#">Push de test</a></li>
                        <li class="divider"></li>
                        <!--<li class="dropdown-header">Dropdown header</li> -->
                        <li><a href="#">Device de test</a></li>
                        <li><a href="#">Version Appli</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/user/disconnect">Disconnect</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Administration</a></li>
                        <li><a href="#">User Groups</a></li>
                        <li><a href="#">Users</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>