<!-- Page title Start -->
      <div class="page-title">
        <div class="row ">
          <!-- Breadcrumb nav start -->
          <div class="col-md-6 col-sm-6 col-xs-6">
              <h2><?php echo(ucfirst($this->pagetitle)); ?></h2>
          <?php /*   <ul class="breadcrumb">
              <li>Chemin</li>
              <li>Form Elements</li>
            </ul> */ ?>
                         
          </div>
          <!-- Breadcrumb nav end -->

          <div class="col-md-6 col-sm-6 col-xs-6">
            
            <!-- Mini Nav Right Start -->
           <?php /* <ul id="page-settings" class="hidden-sm">
               <li id="reportrange">
                <i class="icon-calendar"></i>
                <span></span> <b class="caret"></b>
              </li> 
              <li>
                <i class="icon-cog"></i>
              </li>
            </ul>*/?>
            <!-- Mini Nav Right End -->

            <!-- Stats Start -->
          <?php /*  <ul class="stats hidden-sm hidden-xs">
              <li>
                <span id="orders" class="graph"></span>
                <div class="details">
                  <span class="big">2,591</span>
                  <span class="small">Orders</span>
                </div>
              </li>
              <li>
                <span id="currentBalance" class="graph"></span>
                <div class="details">
                  <span class="big">$7,345</span>
                  <span class="small">Balance</span>
                </div>
              </li>
            </ul> 
            <!-- Stats End -->
           * */ ?>
           
            
          </div>
        </div>
      </div>
      <!-- Page title end -->