<!-- Top bar start -->
<div class="top-bar">

    <div class="logo">
        <sup><a class="brand" href="<?php print($this->url(array('module' => 'Backoffice', 'controller' => 'home', 'action' => 'index'))); ?>"><img src="/web/themes/blackbuck/img/logo.png"></a></sup>
    </div>

    <?php /* Icones de notification
    <!-- Icon nav start -->
    <ul id="icon-nav">
        <li>
            <a href="#">
                <i class="icon-bell"></i>
                <span class="count-label"></span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="icon-comment-alt"></i>
                <span class="count-label count-lb-yellow"></span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="icon-envelope-alt"></i>
                <span class="count-label count-lb-green"></span>
            </a>
        </li>
    </ul>
    <!-- Icon nav end -->

    <!-- Search bar start -->
    <div class="custom-search hidden-xs">
        <input type="text" class="search-query" placeholder="Search here">
        <i class="icon-search"></i>
    </div>
    <!-- Search bar end --> */ ?>

</div>
<!-- Top bar end -->
