 <div class="row-fluid login-wrapper">
        <div class="box">
            <div class="content-wrap">
                <h6>Sign Up</h6>
                <input class="span12" type="text" placeholder="E-mail address">
                <input class="span12" type="password" placeholder="Password">
                <input class="span12" type="password" placeholder="Confirm Password">
                <div class="action">
                    <a class="btn-glow primary signup" href="index.html">Sign up</a>
                </div>                
            </div>
        </div>

        <div class="span4 already">
            <p>Already have an account?</p>
            <a href="signin.html">Sign in</a>
        </div>
    </div>

	<!-- scripts -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="/web/themes/blackbuck/js/bootstrap.min.js"></script>
    <script src="/web/themes/blackbuck/js/theme.js"></script>