<div class="wrapper">
<h1 class="title-page">Conditions générales d'utilisation</h1>
<div class="container" style= margin: auto; font-size: 14px;line-height:1.2">
    <p style="margin-bottom: 20px">
        <i>Version du 3 avril 2013</i>
    </p>

<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="margin-bottom: 0.35cm">Les
pr&eacute;sentes conditions g&eacute;n&eacute;rales d'utilisation
(ci-apr&egrave;s les &laquo; CGUs &raquo;) constituent le contrat
entre vous et SURIKATE SAS, soci&eacute;t&eacute; par actions
simplifi&eacute;e au capital de 3&nbsp;929,00 euros, dont le si&egrave;ge
est situ&eacute; 92-98 Boulevard Victor Hugo &ndash; 92110 CLICHY,
France, immatricul&eacute;e au registre du commerce et des soci&eacute;t&eacute;s
de Paris sous le num&eacute;ro B 523 316 669 (ci-apr&egrave;s &laquo;
Surikate &raquo;) qui exploite le site accessible &agrave; l'adresse
<A HREF="http://www.appliprivee.com">www.appliprivee.com</A>
(ci-apr&egrave;s le &laquo; Site &raquo;), relatif &agrave;
l'utilisation des Applications pour Andro&iuml;d pour iPhone et pour
iPad d&eacute;nomm&eacute;es &laquo; Appli Priv&eacute;e &raquo; et
du site mobile &laquo;&nbsp;m.appliprivee.com&raquo;  d&eacute;velopp&eacute;s
par Surikate (ci-apr&egrave;s l&rsquo;&laquo; Application &raquo;,
devant &ecirc;tre comprise comme l&rsquo;une quelconque des deux
applications pr&eacute;cit&eacute;es et le &laquo;&nbsp;Site
mobile&nbsp;&raquo;). Toute utilisation de l&rsquo;Application et du
Site mobile n&eacute;cessite que vous acceptiez pr&eacute;alablement
les CGUs dans leur int&eacute;gralit&eacute;. Au surplus, vous vous
engagez &agrave; respecter l'ensemble des conditions sp&eacute;cifiques,
notamment le contrat de licence, applicable &agrave; chacun des
logiciels que vous t&eacute;l&eacute;chargez via Appli Priv&eacute;e.
Surikate peut &ecirc;tre ponctuellement amen&eacute; &agrave;
modifier certaines des dispositions de ses CGUs, aussi il est
n&eacute;cessaire que celles-ci soient relues avant chaque visite sur
l'application.</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="margin-bottom: 0.35cm">Article
1 &ndash; <u>Inscription
et acc&egrave;s au Site</u></p>
<p style="margin-bottom: 0.35cm">Afin
de pouvoir effectuer toute sorte d&rsquo;activit&eacute;s et obtenir
des compensations en contrepartie, vous devez vous inscrire via
l&rsquo;Application Appli Priv&eacute;e ou le Site mobile afin de
devenir membre.</p>
<p style="margin-bottom: 0.35cm">En
devenant membre, vous d&eacute;clarez &ecirc;tre domicili&eacute; en
France M&eacute;tropolitaine et &ecirc;tre sous couverture d'un
r&eacute;seau Fran&ccedil;ais, disposer d'un compte bancaire en
France et &ecirc;tre inscrit sur la plate-forme Google Play de Google
Inc. ou iTunes d&rsquo;Apple France Inc. Si vous avez moins de
dix-huit (18) ans, votre inscription et votre utilisation de
l&rsquo;Application et du Site mobile doivent se faire sous la
responsabilit&eacute; et avec l'autorisation de vos parents ou de
votre repr&eacute;sentant l&eacute;gal. Vous vous engagez &agrave;
fournir tout justificatif aff&eacute;rent sur simple demande de
Surikate.</p>
<p style="margin-bottom: 0.35cm">Pour
cela, vous devez renseigner les champs du formulaire d'inscription
avec des donn&eacute;es compl&egrave;tes et exactes. En cas de
d&eacute;claration incompl&egrave;te ou erron&eacute;e, votre compte
peut &ecirc;tre ferm&eacute;, de plein droit, sans pr&eacute;avis et
sans formalit&eacute; pr&eacute;alable et vous consentez &agrave;
garantir Surikate de toutes les cons&eacute;quences qui pourraient
d&eacute;couler de cette d&eacute;claration incompl&egrave;te ou
erron&eacute;e.</p>
<p style="margin-bottom: 0.35cm">L'inscription
est limit&eacute;e &agrave; un compte unique par personne (morale ou
physique). Par cons&eacute;quent, vous vous engagez &agrave; ne pas
cr&eacute;er d'autre compte via notre Application ou notre Site
mobile, pour quelque raison que ce soit. Vous acceptez que Surikate
proc&egrave;de &agrave; des recoupements d'informations afin d'&eacute;viter
toute forme de fraude, en ce compris la cr&eacute;ation de comptes
multiples par une personne.</p>
<p style="margin-bottom: 0.35cm">En
cas de perte de vos identifiants et mots de passe par exemple, vous
ne devez pas cr&eacute;er de nouveau compte, mais contacter
directement Surikate via l'adresse <A HREF="mailto:contact@appliprivee.com">contact@appliprivee.com</A>.
En l'absence d&rsquo;activit&eacute; de votre part apr&egrave;s un
d&eacute;lai raisonnable, ou en cas de non-respect de l'une
quelconque des stipulations des CGUs, Surikate se r&eacute;serve le
droit de suspendre et/ou supprimer votre compte &agrave; tout moment
et sans pr&eacute;avis.</p>
<p style="margin-bottom: 0.35cm">Les
Applications sont obtenues directement sur votre terminal mobile
Andro&iuml;d, votre iPhone ou votre iPad via la plate-forme Google
Play de Google Inc. ou iTunes d&rsquo;Apple Inc. France. Le Site
mobile est accessible depuis tout terminal mobile compatible via un
navigateur Internet sous r&eacute;serve de la souscription d&rsquo;un
forfait ad&eacute;quat. Pour des raisons de s&eacute;curit&eacute; et
de confidentialit&eacute;, il est recommand&eacute; de personnaliser
votre mot de passe. Vos pseudonyme et mot de passe vous sont
personnels et ne doivent pas &ecirc;tre divulgu&eacute;s &agrave; des
tiers. Toute action r&eacute;alis&eacute;e au moyen du pseudonyme et
du mot de passe qui vous correspondent sera r&eacute;put&eacute;e
avoir &eacute;t&eacute; r&eacute;alis&eacute;e par vous. En cas de
divulgation de vos pseudonyme et mot de passe, contactez dans les
plus brefs d&eacute;lais contact@applipriv&eacute;e.com afin que
ceux-ci soient d&eacute;sactiv&eacute;s.</p>
<p style="margin-bottom: 0.35cm">Les
comptes cr&eacute;&eacute;s depuis l&rsquo;Application ou le Site
mobile ne peuvent faire l&rsquo;objet d&rsquo;aucun transfert sur
l&rsquo;Application du m&ecirc;me nom pr&eacute;sente sur tout autre
support, actuel ou futur. Par ailleurs, plusieurs comptes cr&eacute;&eacute;s
sur des supports diff&eacute;rents ne peuvent faire l&rsquo;objet
d&rsquo;aucune fusion ni d&rsquo;aucune forme de regroupement.</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="margin-bottom: 0.35cm">Article
2 &ndash;<u> les
Exp&eacute;riences donnant lieu &agrave; compensation</u></p>
<p style="margin-bottom: 0.35cm">Surikate
vous propose, par l&rsquo;interm&eacute;diaire de ses Applications et
de son Site mobile, de vous r&eacute;compenser pour toutes sortes
d&rsquo;activit&eacute;s (ci-apr&egrave;s les &laquo;&nbsp;Exp&eacute;riences&nbsp;&raquo;).

</p>
<p style="margin-bottom: 0.35cm">Surikate
se r&eacute;serve la possibilit&eacute; de modifier la liste des
Exp&eacute;riences faisant l&rsquo;objet d&rsquo;une compensation.</p>
<p style="margin-bottom: 0.35cm">La
&laquo;&nbsp;compensation&nbsp;&raquo; ne doit pas &ecirc;tre prise
ici au sens du Code Civil mais comme un simple m&eacute;canisme de
fid&eacute;lisation des utilisateurs pour leurs participations aux
exp&eacute;riences. 
</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">2.1
<u>Sondages</u></p>
<p style="margin-bottom: 0.35cm">Afin
que vos participations &agrave; nos Exp&eacute;riences soient
valid&eacute;es, vous devez imp&eacute;rativement vous trouver en
France m&eacute;tropolitaine lorsque vous effectuez les actions
n&eacute;cessaires, tout en &eacute;tant sous couverture d'un r&eacute;seau
fran&ccedil;ais. 
</p>
<p style="margin-bottom: 0.35cm">Pour
obtenir une compensation pour vos Exp&eacute;riences, vous devez
suivre pas &agrave; pas les &eacute;tapes d&eacute;crites dans
l&rsquo;Application ou le Site mobile. La validation des diff&eacute;rentes
&eacute;tapes doit se faire de bonne foi afin d&rsquo;assurer les
r&eacute;ponses les plus compl&egrave;tes et les plus pr&eacute;cises
aux sondages ou aux questions que Surikate pourrait vous proposer.
Vous devez effectuer l&rsquo;ensemble des &eacute;tapes dans le d&eacute;lai
fix&eacute; par Surikate ou, &agrave; d&eacute;faut d&rsquo;informations
particuli&egrave;res, dans le d&eacute;lai  de 24h suivant votre
participation.</p>
<p style="margin-bottom: 0.35cm">Certaines
Exp&eacute;riences peuvent &ecirc;tre soumises &agrave; un nombre
limit&eacute; de participations. Dans un tel cas, lorsque le nombre
de participations sera atteint, le fait de participer &agrave;
l&rsquo;Exp&eacute;rience en cause ne donnera droit &agrave; aucune
compensation.</p>
<p ALIGN=JUSTIFY style="margin-bottom: 0cm; line-height: 100%">Certaines
Exp&eacute;riences sur l&rsquo;Application Andro&iuml;d peuvent ne
pas &ecirc;tre compatibles avec tous les terminaux mobiles. Ainsi
celles-ci peuvent ne pas &ecirc;tre disponibles pour une cat&eacute;gorie
d&rsquo;utilisateurs ayant des terminaux mobiles sp&eacute;cifiques.
Vous reconnaissez avoir pris connaissance de l&rsquo;existence de ce
type d&rsquo;incompatibilit&eacute;s et ne tiendrez en aucun cas
Surikate responsable de celles-ci et des cons&eacute;quences qui
pourraient en d&eacute;couler.</p>
<p style="margin-bottom: 0.35cm">Si
l&rsquo;Exp&eacute;rience consiste en la publication d&rsquo;un avis
ou d&rsquo;un commentaire quelconque suite &agrave; un sondage,
celui-ci doit &ecirc;tre s&eacute;rieux, &eacute;crit dans un langage
correct et intelligible, ne contenir aucun propos litigieux ou
p&eacute;nalement r&eacute;pr&eacute;hensible et &ecirc;tre utile aux
autres utilisateurs. Ces &eacute;crits ne doivent en aucun cas
contrevenir aux stipulations des CGUs et en particulier de l&rsquo;article
2.3.</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">2.2
<u>Autres types
d&rsquo;Exp&eacute;riences</u></p>
<p style="margin-bottom: 0.35cm">Surikate
se r&eacute;serve le droit de vous proposer r&eacute;guli&egrave;rement
de nouvelles Exp&eacute;riences &agrave; effectuer via son
Application ou son Site mobile. 
</p>
<p style="margin-bottom: 0.35cm">Ces
Exp&eacute;riences devront &ecirc;tre effectu&eacute;es selon les
recommandations sp&eacute;cifiques communiqu&eacute;es par Surikate
via les Applications ou le Site mobile et conform&eacute;ment aux
pr&eacute;sentes CGUs. 
</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">2.3
<u>Vos engagements</u></p>
<p style="margin-bottom: 0.35cm">En
l'absence d'autorisation pr&eacute;alable et &eacute;crite de
Surikate, il est interdit :</p>
<p style="margin-bottom: 0.35cm">        D'utiliser
des robots, spiders, crawlers ou autres proc&eacute;d&eacute;s
automatiques d'extraction ou d'examen des pages du Site, du Site
mobile ou de l'Application ;</p>
<p style="margin-bottom: 0.35cm">        De
donner l'impression de quelque mani&egrave;re que ce soit que
Surikate soutient vos produits ou vos services ;</p>
<p style="margin-bottom: 0.35cm">        D'ins&eacute;rer
des informations fausses ou non pertinentes sur le Site, ou dans les
commentaires ;</p>
<p style="margin-bottom: 0.35cm">        De
Publier ou transmettre sur ou par le biais de l&rsquo;Application ou
du Site mobile des contenus &agrave; caract&egrave;re illicite,
mena&ccedil;ant, humiliant, diffamatoire, obsc&egrave;ne, haineux,
pornographique ou blasph&eacute;matoire, ou tout autre message qui
pourrait constituer un crime ou un d&eacute;lit, engager la
responsabilit&eacute; civile, porter atteinte &agrave; la l&eacute;gislation
ou inciter &agrave; le faire, ou encore des contenus qui pourraient
&ecirc;tre utilis&eacute;s &agrave; toute fin contraire &agrave; la
loi ou aux pr&eacute;sentes conditions d'utilisation ;</p>
<p style="margin-bottom: 0.35cm">        D'utiliser
l&rsquo;Application ou le Site mobile de mani&egrave;re &agrave; ce
que, de notre point de vue, les performances ou les fonctionnalit&eacute;s
du Site, de l&rsquo;Application du site d'un tiers, d'un logiciel
tiers, ou de tout autre syst&egrave;me informatique ou r&eacute;seau
utilis&eacute; par Surikate, soient impact&eacute;s n&eacute;gativement
ou que leurs utilisateurs en soient n&eacute;gativement affect&eacute;s
;</p>
<p style="margin-bottom: 0.35cm">        De
charger ou transmettre, sur l&rsquo;Applications ou le Site mobile,
ou utiliser tout &eacute;quipement, logiciel ou routine qui contienne
des virus, chevaux de Troie, vers, bombes &agrave; retardement ou
autres programmes et proc&eacute;d&eacute;s destin&eacute;s &agrave;
endommager, interf&eacute;rer ou tenter d'interf&eacute;rer avec le
fonctionnement normal du Site, ou s'approprier ce Site ou tout
syst&egrave;me, ou encore recourir &agrave; n'importe quel moyen pour
causer une saturation de nos syst&egrave;mes ou porter atteinte aux
droits de tiers.</p>
<p style="margin-bottom: 0.35cm">       De
divulguer au public ou &agrave; un tiers toute information qui
permettrait aux autres utilisateurs de contourner les diff&eacute;rents
dispositifs mis en place par Surikate pour s&rsquo;assurer de
l&rsquo;effectivit&eacute;, de la conformit&eacute; des Exp&eacute;riences
et de la bonne foi des utilisateurs. 
</p>
<p style="margin-bottom: 0.35cm">       
Sont &eacute;galement interdites
toutes les man&oelig;uvres, ou tentatives de man&oelig;uvres, ayant
pour objet de d&eacute;tourner de leur usage normal tout ou partie
des logiciels mis &agrave; disposition par Surikate. Surikate se
r&eacute;serve le droit de suspendre de mani&egrave;re pr&eacute;ventive
tout compte suspect&eacute; d&rsquo;avoir servi &agrave; la
commission de telles man&oelig;uvres frauduleuses et de le supprimer
si la fraude est av&eacute;r&eacute;e et ce, sans pr&eacute;avis. 
</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="margin-bottom: 0.35cm">Il
est rappel&eacute; que les articles 323-1 et suivants du Code p&eacute;nal
sanctionnent par des peines allant jusqu'&agrave; cinq (5) ans
d'emprisonnement et 75 000 euros d'amende, notamment :</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">L'acc&egrave;s
et le maintien frauduleux dans un syst&egrave;me de traitement
automatis&eacute; de donn&eacute;es ;</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">La
suppression, la modification ou l'ajout frauduleux de donn&eacute;es
dans ce syst&egrave;me ;</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">Le
fait d'entraver ce syst&egrave;me.</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="margin-bottom: 0.35cm">Article
3 - <u>Compensation</u></p>
<p style="margin-bottom: 0.35cm">En
contrepartie des Exp&eacute;riences que vous effectuez et pour
r&eacute;compenser votre fid&eacute;lit&eacute;, Surikate peut vous
offrir une compensation dans les conditions d&eacute;finies par les
CGUs. 
</p>
<p style="margin-bottom: 0.35cm">Ces
compensations ne constituent qu&rsquo;une incitation et ne peuvent en
aucun cas s&rsquo;analyser en une r&eacute;mun&eacute;ration des
utilisateurs, Surikate se r&eacute;servant le droit de modifier, &agrave;
tout moment, les conditions d&rsquo;attribution de celles-ci. 
</p>
<p style="margin-bottom: 0.35cm">Les
compensations sont toujours indiqu&eacute;es en euros toutes taxes
comprises et hors frais annexes.</p>
<p style="margin-bottom: 0.35cm">La
compensation applicable &agrave; chaque Exp&eacute;rience est
indiqu&eacute;e sur l&rsquo;Application ou le Site mobile dans la
liste d&rsquo;Exp&eacute;riences disponibles, avant que vous ne
validiez votre participation.</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">3.1
<u>Condition d&rsquo;&eacute;ligibilit&eacute;</u></p>
<p style="margin-bottom: 0.35cm">Aucune
Exp&eacute;rience ne peut faire l&rsquo;objet d&rsquo;une
compensation si toutes les &eacute;tapes n&rsquo;ont pas &eacute;t&eacute;
valid&eacute;es de bonne foi conform&eacute;ment aux recommandations
sp&eacute;cifiques qui vous sont communiqu&eacute;es via
l&rsquo;Application ou le Site mobile. 
</p>
<p style="margin-bottom: 0.35cm">Tout
manquement aux CGUs et/ou &agrave; la l&eacute;gislation applicable
autorise Surikate &agrave; annuler toute compensation qui vous serait
&eacute;ventuellement due, y compris si celle-ci a d&eacute;j&agrave;
&eacute;t&eacute; cr&eacute;dit&eacute;e sur votre compte Appli
Priv&eacute;e, &agrave; tout moment et sans pr&eacute;avis.</p>
<p style="margin-bottom: 0.35cm">Toute
r&eacute;clamation concernant le versement de vos compensations devra
parvenir &agrave; Surikate dans un d&eacute;lai maximum de deux (2)
mois, &agrave; compter de l&rsquo;expiration du d&eacute;lai stipul&eacute;
dans l&rsquo;article 3.2, et devra obligatoirement contenir vos
donn&eacute;es d&rsquo;identification, sous peine de ne pouvoir faire
l&rsquo;objet d&rsquo;un traitement effectif. 
</p>
<p style="margin-bottom: 0.35cm">Au-del&agrave;
de ce d&eacute;lai, aucune r&eacute;clamation ne sera trait&eacute;e
et les compensations &eacute;ventuellement concern&eacute;es seront
d&eacute;finitivement perdues. 
</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">3.2
<u>Compensation financi&egrave;re</u></p>
<p style="margin-bottom: 0.35cm">Pour
certaines Exp&eacute;riences, la compensation consiste dans le
versement d'une somme d'argent. Ces sommes sont inscrites sur votre
compte Appli Priv&eacute;e dans un d&eacute;lai de trente (30) jours
&agrave; compter de la validation de votre Exp&eacute;rience. 
</p>
<p style="margin-bottom: 0.35cm">Vous
pouvez demander &agrave; percevoir vos compensations uniquement par :</p>
<p style="margin-left: 1.27cm; margin-bottom: 0.35cm"><br><br>
</p>
<UL>
	<LI><p style="margin-bottom: 0.35cm">Virement
	bancaire. Vous devez pour cela disposer d&rsquo;un compte bancaire
	dans un &eacute;tablissement agr&eacute;&eacute;, permettant
	d&rsquo;effectuer ce type d&rsquo;op&eacute;rations, ainsi qu&rsquo;un
	RIB associ&eacute; &agrave; ce compte bancaire, sous r&eacute;serve
	que le montant de vos compensations soit &eacute;gal ou sup&eacute;rieur
	&agrave; un palier fix&eacute; par Surikate.</p>
</UL>
<p style="margin-left: 1.27cm; margin-bottom: 0.35cm"><br><br>
</p>
<UL>
	<LI><p style="margin-bottom: 0.35cm">Conversion
	des compensations accumul&eacute;es en codes de cartes iTunes ou
	codes de ch&egrave;ques cadeaux Amazon, sous r&eacute;serve que le
	montant de vos compensations soit &eacute;gal ou sup&eacute;rieur &agrave;
	un palier fix&eacute; par Surikate.</p>
</UL>
<p style="margin-left: 1.27cm; margin-bottom: 0.35cm">Vous
recevrez ces codes au sein m&ecirc;me de nos Applications ou de notre
Site mobile.</p>
<p style="margin-bottom: 0.35cm">Surikate
se r&eacute;serve la possibilit&eacute; de modifier de fa&ccedil;on
discr&eacute;tionnaire les montants associ&eacute;s aux diff&eacute;rents
paliers de perception ainsi que les diff&eacute;rents modes de
perception de vos compensations, et ce sans pr&eacute;avis. 
</p>
<p style="margin-bottom: 0.35cm">Par
ailleurs, vous reconnaissez que Surikate ne saurait &ecirc;tre tenue
de d&eacute;livrer le solde de votre compte par un autre moyen que
ceux mentionn&eacute;s ci-dessus. 
</p>
<p style="margin-bottom: 0.35cm">Vous
recevrez vos compensations dans un d&eacute;lai de trente (30) jours
apr&egrave;s r&eacute;ception de votre demande de perception par
Surikate. 
</p>
<p style="margin-bottom: 0.35cm">Vous
pouvez acc&eacute;der au solde de votre compte &agrave; tout moment
en vous connectant sur l&rsquo;Application ou le Site mobile.</p>
<p style="margin-bottom: 0.35cm">Vous
&ecirc;tes express&eacute;ment inform&eacute; qu'&agrave; l'issue
d'une p&eacute;riode de 3 mois d'inactivit&eacute;, le solde de votre
compte Appli Priv&eacute;e sera d&eacute;finitivement perdu. Est
consid&eacute;r&eacute;e comme une p&eacute;riode d&rsquo;inactivit&eacute;
l&rsquo;absence totale de participation effective &agrave; une
Exp&eacute;rience durant la p&eacute;riode d&eacute;finie ci-dessus. 
</p>
<p style="margin-bottom: 0.35cm">A
l&rsquo;issue de cette p&eacute;riode d&rsquo;inactivit&eacute;,
votre compte Appli Priv&eacute; et toutes les informations s&rsquo;y
rapportant seront d&eacute;finitivement supprim&eacute;es. 
</p>
<p style="margin-bottom: 0.35cm">Surikate
ne pourra, en tout &eacute;tat de cause, &ecirc;tre tenue pour
responsable de la perte pour inactivit&eacute; de la totalit&eacute;
ou d&rsquo;une partie des sommes cr&eacute;dit&eacute;es jusqu&rsquo;alors.

</p>
<p style="margin-bottom: 0.35cm">Toute
r&eacute;clamation concernant la perception de vos compensations
devra parvenir &agrave; Surikate dans un d&eacute;lai maximum de deux
(2) mois &agrave; compter de l&rsquo;expiration du d&eacute;lai de
trente (30) jours et devra n&eacute;cessairement contenir vos donn&eacute;es
d&rsquo;identification sous peine de ne pouvoir faire l&rsquo;objet
d&rsquo;un traitement effectif. 
</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="margin-bottom: 0.35cm">Article
4 - <u>Propri&eacute;t&eacute;
intellectuelle</u></p>
<p style="margin-bottom: 0.35cm">La
participation aux services propos&eacute;s par Surikate se fait
n&eacute;cessairement via les Applications, le Site mobile ou le
Site, ce qui n&eacute;cessite le t&eacute;l&eacute;chargement et
l'acceptation en int&eacute;gralit&eacute; des conditions
d'utilisation de ceux-ci telles que d&eacute;finies ci-apr&egrave;s.</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">4.1
<u>Droit d'usage de
l&rsquo;Application et du Site mobile</u></p>
<p style="margin-bottom: 0.35cm">Surikate
vous accorde un droit d'utilisation personnel, non exclusif, non
transf&eacute;rable et non cessible, des Applications et du Site
mobile pour le Monde entier et pour la dur&eacute;e de protection des
Applications et du Site mobile par les droits de propri&eacute;t&eacute;
intellectuelle correspondants, dans les conditions et limites
sp&eacute;cifi&eacute;es ci-apr&egrave;s.</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">4.2
<u>Limitations &agrave;
l'usage des Applications, du Site mobile et du Site</u></p>
<p style="margin-bottom: 0.35cm">L&rsquo;utilisateur
s'interdit, directement ou indirectement, et s'engage &agrave;
interdire &agrave; toute personne amen&eacute;e &agrave; utiliser
l&rsquo;Application ou le Site mobile :</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">De
d&eacute;compiler, d&eacute;sassembler l&rsquo;Application ou le Site
mobile, de pratiquer l'ing&eacute;nierie inverse ou de tenter de
d&eacute;couvrir ou reconstituer le code source, les id&eacute;es qui
en sont la base, les algorithmes, les formats des fichiers ou les
interfaces de programmation ou d'interop&eacute;rabilit&eacute; de
l'Application ou du Site mobile sauf dans la limite du droit accord&eacute;
par l'article L. 122-6-1 du Code de la propri&eacute;t&eacute;
intellectuelle, de quelque mani&egrave;re que ce soit. Au cas o&ugrave;
vous souhaiteriez obtenir les informations permettant de mettre en
&oelig;uvre l'interop&eacute;rabilit&eacute; de l'Application ou du
Site mobile avec un autre logiciel d&eacute;velopp&eacute; ou acquis
de mani&egrave;re ind&eacute;pendante par vous et ce pour un emploi
conforme &agrave; la destination de l'Application ou du Site mobile,
vous vous engagez, avant de faire appel &agrave; un tiers, &agrave;
consulter pr&eacute;alablement Surikate qui pourra vous fournir les
informations n&eacute;cessaires &agrave; la mise en &oelig;uvre de
cette interop&eacute;rabilit&eacute;. Le co&ucirc;t exact engendr&eacute;
en interne chez Surikate pour la fourniture de ces informations vous
sera factur&eacute; par Surikate ;</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">D'effectuer
toute autre utilisation de l'Application ou du Site mobile que celle
permise dans le cadre des CGUs ;</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">De
traduire, adapter, arranger, modifier l'Application ou le Site mobile
de quelque mani&egrave;re que ce soit, de l'int&eacute;grer ou de
l'associer avec d'autres logiciels ou de cr&eacute;er des &oelig;uvres
composites ou d&eacute;riv&eacute;es avec l'aide de tout ou partie de
l'Application ou du Site mobile ;</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">De
proc&eacute;der seul, ou avec l'aide d'un tiers prestataire, &agrave;
la correction des &eacute;ventuelles erreurs de l'Application ou du
Site mobile pour le rendre conforme &agrave; sa destination, Surikate
se r&eacute;servant seul l'exercice de ce droit conform&eacute;ment &agrave;
l'article L. 122-6-1-I du Code de la propri&eacute;t&eacute;
intellectuelle.</p>
<p style="margin-bottom: 0.35cm">En
utilisant les services propos&eacute;s par Surikate et en
t&eacute;l&eacute;chargeant ou utilisant l'Application ou le Site
mobile, vous reconnaissez avoir accept&eacute; lesdites conditions.</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">4.3
<u>Droits de propri&eacute;t&eacute;
intellectuelle de Surikate</u></p>
<p style="margin-bottom: 0.35cm"><A NAME="_GoBack"></A>Le
Site, le Site mobile et les Applications sont la propri&eacute;t&eacute;
exclusive de Surikate. Surikate vous accorde un droit gratuit,
personnel, non-exclusif et non-transf&eacute;rable d'acc&egrave;s et
d'utilisation du Site, du Site mobile et des Applications dans les
limites d&eacute;finies au sein des CGUs.</p>
<p style="margin-bottom: 0.35cm">Tout
contenu n'&eacute;tant pas mis en ligne par un membre du Site,
notamment toute donn&eacute;e, fonctionnalit&eacute;, texte, noms,
d&eacute;signations, image, photographies, &eacute;l&eacute;ment
graphique, marques, sons, est la propri&eacute;t&eacute; exclusive de
Surikate ou de ses licenci&eacute;s. Les CGUs ne sauraient en aucun
cas &ecirc;tre interpr&eacute;t&eacute;es comme un transfert de l'un
quelconque des droits de Surikate. Aucun de ces &eacute;l&eacute;ments
ne peut &ecirc;tre t&eacute;l&eacute;charg&eacute;, copi&eacute;,
modifi&eacute;, supprim&eacute;, distribu&eacute;, transmis, diffus&eacute;,
vendu, lou&eacute;, conc&eacute;d&eacute; ou exploit&eacute; de
quelque mani&egrave;re que ce soit, sans l'accord expr&egrave;s,
pr&eacute;alable et &eacute;crit de Surikate ou de ses licenci&eacute;s.</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">4.4
<u>Votre contenu</u></p>
<p style="margin-bottom: 0.35cm">Vous
acceptez express&eacute;ment que Surikate puisse r&eacute;utiliser
vos contenus dans le cadre de son activit&eacute;, et vous vous
engagez &agrave; c&eacute;der &agrave; Surikate l'ensemble des droits
patrimoniaux sur ces contenus. Les droits ainsi c&eacute;d&eacute;s
par le membre &agrave; Surikate comprennent : (i) le droit de
reproduction, qui est d&eacute;fini comme le droit de r&eacute;aliser
ou de faire r&eacute;aliser un nombre illimit&eacute; de copies des
commentaires sur tout support, de toute nature, connu ou inconnu &agrave;
ce jour et notamment sur internet et sur support &eacute;crit,
num&eacute;rique, informatique ou vid&eacute;o ; (ii) le droit de
repr&eacute;sentation, qui est d&eacute;fini comme le droit de
communiquer, diffuser, faire communiquer ou faire diffuser les
commentaires aupr&egrave;s du public, sous toutes formes de diffusion
(notamment internet, t&eacute;l&eacute;vision, tous produis ou
appareils, lors de spectacles et/ou repr&eacute;sentations ; (iii) le
droit de modification et d'adaptation des commentaires, en tout ou
partie, sans limitation de formats ou de coloris ; (iv) le droit de
traduire les commentaires en toute langue, y compris tout langage
informatique ; (v) le droit de corriger les commentaires ; et (vi) le
droit d'exploiter les commentaires dans le cadre de toute utilisation
commerciale et non-commerciale, publicitaire et/ou promotionnelle, de
les distribuer, &eacute;diter, vendre, c&eacute;der, louer, mettre en
circulation, &agrave; titre gratuit ou on&eacute;reux, par tous les
circuits de distribution connus ou inconnus &agrave; ce jour. Vous
vous engagez par ailleurs express&eacute;ment &agrave; r&eacute;it&eacute;rer
ladite cession sur simple demande de Surikate.</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="margin-bottom: 0.35cm">Article
5 - <u>Garanties</u></p>
<p style="margin-bottom: 0.35cm">Surikate
garantit que l&rsquo;Application et le Site mobile se t&eacute;l&eacute;charge
sur votre appareil, sous r&eacute;serve (i) du respect des conditions
applicables &agrave; votre relation avec votre op&eacute;rateur, (ii)
du bon fonctionnement des r&eacute;seaux de communication
&eacute;lectronique et (iii) du bon fonctionnement de votre appareil.</p>
<p style="margin-bottom: 0.35cm">Vous
garantissez que le commentaire que vous laissez est original,
conforme aux stipulations des CGUS, ne contrevient pas &agrave; la
l&eacute;gislation applicable et ne porte atteinte aux droits d'un
tiers. Vous vous engagez &agrave; garantir, relever et indemniser
Surikate de toutes condamnations, co&ucirc;ts et/ou frais (en ce
compris les frais de justice et d'avocats) qu'elle supporterait
d&eacute;coulant de toute demande, action ou r&eacute;clamation en
relation avec un ou plusieurs commentaires dont vous seriez l'auteur.</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="margin-bottom: 0.35cm">Article
6 - <u>Responsabilit&eacute;</u></p>
<p style="margin-bottom: 0.35cm">Dans
toute la mesure permise par la loi, il est express&eacute;ment
convenu entre les Parties que Surikate exclut toute responsabilit&eacute;
dans le cadre de la fourniture de ses services, du Site, du Site
mobile et de l'Application et en particulier la responsabilit&eacute;
du fait des produits d&eacute;fectueux telle que d&eacute;finie aux
articles 1386-1 et suivants du Code civil. En toutes hypoth&egrave;ses,
si la responsabilit&eacute; de Surikate devait &ecirc;tre engag&eacute;e,
Surikate ne saurait &ecirc;tre tenue responsable que des dommages
directs et pr&eacute;visibles au sens des articles 1150 et 1151 du
Code Civil engendr&eacute;s par une d&eacute;faillance ou un mauvais
fonctionnement du Logiciel. Surikate ne saurait en aucune
circonstance encourir de responsabilit&eacute; au titre des dommages
indirects ou impr&eacute;visibles. Il est express&eacute;ment convenu
entre les Parties que Surikate ne saurait &ecirc;tre responsable de
tout gain manqu&eacute;, perte de chiffre d'affaires ou de b&eacute;n&eacute;fice,
perte de client&egrave;le, perte d'une chance, co&ucirc;t de
l'obtention d'un produit, d'un logiciel, d'un service ou d'une
technologie de substitution.</p>
<p style="margin-bottom: 0.35cm">Surikate
s'engage exclusivement &agrave; respecter les dispositions l&eacute;gales
applicables en vigueur en France. Aucune r&eacute;glementation propre
au pays de livraison et/ou de consultation du Site ne pourra &ecirc;tre
oppos&eacute;e.</p>
<p style="margin-bottom: 0.35cm">Le
Site, le Site mobile et l'Application sont accessibles 24 heures/24
et 7 jours/7, sous r&eacute;serve de leur fermeture pour maintenance
ou en cas de force majeure ou de tout &eacute;v&eacute;nement
&eacute;chappant &agrave; notre contr&ocirc;le. La force majeure est
d&eacute;finie par la jurisprudence des juridictions fran&ccedil;aises
comme tout &eacute;v&eacute;nement impr&eacute;visible, irr&eacute;sistible
et ext&eacute;rieur, totalement ind&eacute;pendant de la volont&eacute;
et du contr&ocirc;le des parties, incluant, sans limitation, toute
r&eacute;glementation d'une autorit&eacute; &eacute;tatique ou
supranationale, un &eacute;tat de guerre ou d'urgence, une
catastrophe naturelle, un acte terroriste, un incendie, un mouvement
de gr&egrave;ve du personnel d'un prestataire de services ou bien une
d&eacute;faillance des r&eacute;seaux de communications
&eacute;lectroniques.</p>
<p style="margin-bottom: 0.35cm">Vous
acceptez les limites de l'Internet et des moyens de communications
&eacute;lectroniques. En cons&eacute;quence, Surikate ne saurait &ecirc;tre
tenue responsable de toute indisponibilit&eacute; du Site, du Site
mobile ou de l'Application, ou de toute difficult&eacute; de
connexion ou d'interruption de la connexion lors de votre visite du
Site ou votre utilisation de l'Application ou du Site mobile.</p>
<p style="margin-bottom: 0.35cm">Les
photos et illustrations propos&eacute;es sur l'Application, le Site
mobile et les autres supports de communication ne constituent pas une
description contractuelle des caract&eacute;ristiques des logiciels.
Les logiciels qui vous sont livr&eacute;s peuvent diff&eacute;rer des
illustrations qui sont propos&eacute;es.</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="margin-bottom: 0.35cm">Article
7 - <u>Protection des
donn&eacute;es &agrave; caract&egrave;re personnel</u></p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">7.1
<u>Finalit&eacute;s du
traitement</u></p>
<p style="margin-bottom: 0.35cm">En
vous inscrivant sur l&rsquo;Application ou le Site mobile, vous
acceptez de communiquer vos donn&eacute;es &agrave; caract&egrave;re
personnel (nom, pr&eacute;nom, sexe, adresse e-mail, date de
naissance, UDID et MAC adress de votre appareil, centres d'int&eacute;r&ecirc;t&hellip;)
pour les finalit&eacute;s suivantes :</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">Le
traitement des commandes ;</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">La
gestion et le versement des compensations 
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">La
r&eacute;ception d'offres promotionnelles de la part de Surikate pour
des produits ou services similaires &agrave; ceux que vous avez
pr&eacute;c&eacute;demment command&eacute;s 
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">La
r&eacute;ception de nos lettres d'information.</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">7.2
<u>Destinataires du
traitement</u></p>
<p style="margin-bottom: 0.35cm">Dans
certaines circonstances particuli&egrave;res, Surikate peut &ecirc;tre
amen&eacute; &agrave; divulguer vos donn&eacute;es &agrave; caract&egrave;re
personnel, lorsque celles-ci sont exig&eacute;es par les autorit&eacute;s
judiciaires.</p>
<p style="margin-bottom: 0.35cm">Vos
donn&eacute;es &agrave; caract&egrave;re personnel, et notamment les
adresses de courrier &eacute;lectronique, ne font l'objet d'aucune
location, vente, &eacute;change ou partage avec d'autres prestataires
si vous n'avez pas accept&eacute; de recevoir des offres
promotionnelles de la part d'autres soci&eacute;t&eacute;s
susceptibles de vous int&eacute;resser.</p>
<p style="margin-bottom: 0.35cm">Surikate
se r&eacute;serve la possibilit&eacute; de c&eacute;der ou de
transf&eacute;rer certaines donn&eacute;es anonymes (comme l&rsquo;&acirc;ge,
le sexe, les centres d&rsquo;int&eacute;r&ecirc;ts&hellip;) dans le
cadre de contrats conclus avec des tiers &agrave; des fins marketing.

</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">7.3
<u>Conservation des
donn&eacute;es</u></p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">Surikate
conserve vos donn&eacute;es &agrave; caract&egrave;re personnel pour
la dur&eacute;e strictement n&eacute;cessaire &agrave; la r&eacute;alisation
des finalit&eacute;s vis&eacute;es ci-avant. Au-del&agrave; de cette
dur&eacute;e, elles seront conserv&eacute;es &agrave; des fins
exclusivement statistiques et ne donneront lieu &agrave; aucune
exploitation, de quelle que nature que ce soit.</p>
<p style="margin-bottom: 0.35cm">Surikate
a aussi l'obligation de conserver les donn&eacute;es permettant
l'identification des internautes mettant &agrave; disposition des
contenus, et ce aux fins de transmission de ces donn&eacute;es aux
autorit&eacute;s comp&eacute;tentes sur r&eacute;quisition
judiciaire, &agrave; l'exclusion de tout autre tiers, et dans les
conditions pr&eacute;vues par la loi.</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">7.4
<u>Vos droits</u></p>
<p style="margin-bottom: 0.35cm">Toutes
les donn&eacute;es &agrave; caract&egrave;re personnel que vous
communiquez &agrave; Surikate sont strictement confidentielles. Elles
sont n&eacute;cessaires en vue du t&eacute;l&eacute;chargement des
logiciels mis &agrave; votre disposition sur le site. &Agrave; tout
moment, vous pouvez acc&eacute;der &agrave; vos donn&eacute;es &agrave;
caract&egrave;re personnel et mettre &agrave; jour ces informations
prot&eacute;g&eacute;es gr&acirc;ce &agrave; vos identifiants (email
et/ou pseudo) et &agrave; votre mot de passe. 
</p>
<p style="margin-bottom: 0.35cm">Conform&eacute;ment
&agrave; la loi n&deg;78-17 du 6 janvier 1978 relative &agrave;
l'informatique, aux fichiers et aux libert&eacute;s, le traitement
des informations nominatives collect&eacute;es sur le site a fait
l'objet d'une d&eacute;claration aupr&egrave;s de la Commission
Nationale de l'Informatique et des Libert&eacute;s. Vous disposez
d'un droit d'acc&egrave;s, de modification, de rectification et de
suppression des donn&eacute;es vous concernant.</p>
<p style="margin-bottom: 0.35cm">Pour
exercer l'un de vos droits, Il vous suffit d'&eacute;crire &agrave;
l'adresse suivante Surikate SAS 92-98 Boulevard Victor Hugo, 92110
CLICHY, en indiquant nom, pr&eacute;nom, adresse de courrier
&eacute;lectronique et, le cas &eacute;ch&eacute;ant, num&eacute;ro
UDID. 
</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">7.5
<u>Cookies</u></p>
<p style="margin-bottom: 0.35cm">Le
site utilise des cookies afin de vous &eacute;viter de saisir vos
identifiants et mots de passe &agrave; chaque visite et afin de
faciliter la passation des commandes. 
</p>
<p style="margin-bottom: 0.35cm">Vous
conservez la possibilit&eacute; de refuser les cookies en configurant
les param&egrave;tres de votre terminal mobile ou de votre navigateur
Internet. 
</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="text-indent: 1.25cm; margin-bottom: 0.35cm">7.6
<u>Utilisation statistique
de donn&eacute;es anonymes</u></p>
<p style="margin-bottom: 0.35cm">Dans
le cadre de son activit&eacute;, Surikate collecte, traite et stocke
des donn&eacute;es statistiques relatives &agrave; l'utilisation des
Logiciels. Ces donn&eacute;es sont transmises aux Editeurs afin
notamment de leur permettre d'am&eacute;liorer leurs produits.</p>
<p style="margin-bottom: 0.35cm">Ces
donn&eacute;es d'utilisation sont anonymes et ne permettent en aucun
cas de vous identifier, m&ecirc;me de mani&egrave;re indirecte.</p>
<p style="margin-bottom: 0.35cm"><br><br>
</p>
<p style="margin-bottom: 0.35cm">Article
8 - <u>Stipulations
diverses</u></p>
<p style="margin-bottom: 0.35cm">Le
fait que vous ou Surikate n'exerce pas l'un quelconque de nos droits
au titre des conditions g&eacute;n&eacute;rales d'utilisation ne
saurait emporter renonciation de notre part ou de votre part &agrave;
ce droit, une telle renonciation ne pouvant proc&eacute;der que d'une
d&eacute;claration expresse.</p>
<p style="margin-bottom: 0.35cm">Dans
l'hypoth&egrave;se o&ugrave; une ou plusieurs stipulations des CGUs
seraient consid&eacute;r&eacute;es comme non valides par une
juridiction comp&eacute;tente, les autres stipulations conserveront
leur port&eacute;e et effet.</p>
<p style="margin-bottom: 0.35cm">Les
registres informatis&eacute;s seront conserv&eacute;s dans les
syst&egrave;mes informatiques de Surikate dans des conditions
raisonnables de s&eacute;curit&eacute; et seront consid&eacute;r&eacute;s
comme des preuves des &eacute;changes, des commandes et des paiements
intervenus via l'Application, le Site mobile ou par courrier
&eacute;lectronique.</p>
<p style="margin-bottom: 0.35cm">Surikate
se r&eacute;serve la possibilit&eacute;, dans les limites permises
par la loi, et notamment les dispositions de l'article R132-1 du Code
de la consommation, de modifier les CGUs &agrave; tout moment.
Lorsque les conditions g&eacute;n&eacute;rales sont modifi&eacute;es,
les termes amend&eacute;s sont applicables d&egrave;s leur
publication sur le Site. Chaque utilisation de l'Application ou du
Site mobile sera alors soumise aux CGUs applicables &agrave; ce
moment.</p>
<p style="margin-bottom: 0.35cm">Les
pr&eacute;sentes CGUs sont r&eacute;gies par le droit fran&ccedil;ais.
Le non-respect de l'une quelconque des dispositions des CGUs et de
fa&ccedil;on plus g&eacute;n&eacute;rale toute difficult&eacute;
touchant &agrave; leur ex&eacute;cution, leur interpr&eacute;tation
ou leur validit&eacute;, sont soumises aux juridictions fran&ccedil;aises.</p>
    
    
</div>
</div>