<table><tr><td></td></tr>
<?php if($this->type=='reporting_select_mainPlacement') { ?> 
	<tr><td>
		<select id="placementField" name="placementField" class="select2">
		    <option value="">Select Placement</option>
			<option value="0">All Placements</option>
		    <?php foreach ($this->placement as $key=>$value): ?>
		            <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
		             <?php endforeach; ?> 
		</select>
	</td></tr>
<?php }if($this->type=='reporting_select_mainCampaign') { ?>
	<tr><td>
		<select id="campaignField" name="campaignField" class="select2">
			<option value="">Select Campaign</option>
			<option value="0">All Campaigns</option>
			    <?php foreach ($this->campaign as $key=>$value): ?>
			            <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
			             <?php endforeach; ?> 
		</select>
	</td></tr>
<?php }?>
<?php if($this->type=='listsecondSelect'){?>
	<tr><td>
		<select id="secondField" name="secondField" class="select2">
		    <?php foreach ($this->secondField as $key=>$value): if($key){?>
		            <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
		             <?php }endforeach; ?> 
		</select>
	</td></tr>
	<tr><td>
		<select id="thirdField" name="thirdField" class="select2">
		    <?php foreach ($this->secondField as $key=>$value): ?>
		            <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
		             <?php endforeach; ?> 
		</select>
	</td></tr>
	<tr><td>
		<select id="fourthField" name="fourthField" class="select2">
		    <?php foreach ($this->secondField as $key=>$value): ?>
		            <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
		             <?php endforeach; ?> 
		</select>
	</td></tr>
	<tr><td>
	<select id="fifthField" name="fifthField" class="select2">
	    <?php foreach ($this->secondField as $key=>$value): ?>
	            <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
	             <?php endforeach; ?> 
	</select>
	</td></tr>
</table>
<?php }?>