<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h2 class="panel-title"><?php print(_('Delete Group')) ?></h2>
            </div>
            <div class="panel-body">
                <p>Confirme ?</p>
                <?php echo($this->form); ?>
            </div>
        </div>
    </div>
</div>