<div class="cgu">

	<div class="title container dark">
		<h1 class="h1">
			<span class="separator"><span class="hr"></span></span> <span class="text ico"><?php echo(_('Terms of Use'));?>
			</span> <span class="separator"><span class="hr"></span></span>
		</h1>
	</div>

	<div class="container">
		<div class="privacypolicy">
			<h3>SK United Limited ("We") are committed to protecting and
				respecting your privacy.</h3>
			<p>
				This policy (and any other documents referred to on it) sets out the
				basis on which any personal data we collect from you, or that you
				provide to us, will be processed by us. Please read the following
				carefully to understand our views and practices regarding your
				personal data and how we will treat it.<br> <br> For the purpose of
				the Data Protection Act 1998 (the "Act"), the data controller is SK
				United Limited of 10 St Bride Street, London EC4A 4AD.<br>
			</p>
			<h3>INFORMATION WE MAY COLLECT FROM YOU</h3>
			<p>
				We may collect and process the following data about you:<br> <br>
				Information that you provide by filling in forms on our site
				www.appxpert.co.uk ("our Site") or on our applications ("Our
				Applications") This includes information such as name, address,
				email address, date of birth, Paypal account details <?php /*, UDID and Mac
				Address of your iPhone, iPad or iPod Touch ("iDevice") */ ?> provided at
				the time of registering to use our Site or our Applications.<br> <br>
				If you contact us, we may keep a record of that correspondence.<br>
				<br> We may collect additional information at other times, including
				but not limited to, when you provide feedback, change your content
				or email preferences, report a problem with our Site or Our
				Applications, or respond voluntarily to any survey that we use for
				research purposes.<br> <br> Details of transactions you carry out
				through our Site or Applications and of the fulfilment of your
				orders. To fulfil your order, we collect your address or billing
				information, including your Paypal account details.<br> <br> Details
				of your visits to our Site including, but not limited to, traffic
				data, location data, weblogs and other communication data, whether
				this is required for our own billing purposes or otherwise and the
				resources that you access.<br>
			</p>
			<h3>IP ADDRESSES</h3>
			<p>
				We may collect information about your computer, including where
				available your IP address, operating system and browser type for
				system administration and to report aggregated information to our
				advertisers. This is statistical data about our users' browsing
				actions and patterns, and does not identify any individual.<br>
			</p>
			<h3>WHERE WE STORE YOUR PERSONAL DATA</h3>
			<p>
				The data that we collect from you may be transferred to, and stored
				at, a destination outside the European Economic Area ("EEA"). It may
				also be processed by staff operating outside the EEA who work for us
				or for one of our suppliers. Such staff maybe engaged in, among
				other things, the fulfilment of your order, the processing of the
				payment of rewards and the provision of support services. By
				submitting your personal data, you agree to this transfer, storing
				or processing. We will take all steps reasonably necessary to ensure
				that your data is treated securely and in accordance with this
				privacy policy.<br> <br> All information you provide to us is stored
				on our secure servers. Any payment transactions will be encrypted
				using SSL technology. Where we have given you (or where you have
				chosen) a password which enables you to access certain parts of our
				site, you are responsible for keeping this password confidential. We
				ask you not to share such password with anyone and cannot be held
				responsible for its misuse where you have so shared it.<br> <br>
				Unfortunately, the transmission of information via the internet is
				not completely secure. Although we will do our best to protect your
				personal data, we cannot guarantee the security of your data
				transmitted to our site; any transmission is at your own risk. Once
				we have received your information, we will use strict procedures and
				security features to try to prevent unauthorised access.<br>
			</p>
			<h3>INFORMATION ABOUT OUR USE OF COOKIES</h3>
			<p>
				Our website uses cookies to distinguish you from other users of our
				website. This helps us to provide you with a good experience when
				you browse our website and also allows us to improve our site. <br>
				<br> A cookie is a small file of letters and numbers that we store
				on your browser or the hard drive of your computer if you agree.
				Cookies contain information that is transferred to your computer's
				hard drive.<br>
				<br> We use the following cookies:<br>
				<br> Strictly necessary cookies. These are cookies that are required
				for the operation of our website. They include, for example, cookies
				that enable you to log into secure areas of our website, use a
				shopping cart or make use of e-billing services.<br>
				<br> Analytical/performance cookies. They allow us to recognise and
				count the number of visitors and to see how visitors move around our
				website when they are using it. This helps us to improve the way our
				website works, for example, by ensuring that users are finding what
				they are looking for easily.<br>
				<br> Functionality cookies. These are used to recognise you when you
				return to our website. This enables us to personalise our content
				for you, greet you by name and remember your preferences (for
				example, your choice of language or region).<br>
				<br> Targeting cookies. These cookies record your visit to our
				website, the pages you have visited and the links you have followed.
				We will use this information to make our website and the advertising
				displayed on it more relevant to your interests. We may also share
				this information with third parties for this purpose.<br>
				<br> You can find more information about the individual cookies we
				use and the purposes for which we use them in the table below:
			</p>
			
			<h3>USES MADE OF THE INFORMATION</h3>
			<p>
				We use information held about you in the following ways:<br> <br> To
				ensure that content from our Site is presented in the most effective
				manner for you and for your computer.<br> <br> To send you by e-mail
				our weekly newsletter<br> <br> To provide you with information,
				products or services that you request from us or which we feel may
				interest you, where you have consented to be contacted for such
				purposes.<br> <br> To carry out our obligations arising from any
				contracts entered into between you and us.<br> <br> To allow you to
				participate in interactive features of our service, when you choose
				to do so.<br> <br> To notify you about changes to our service.<br>
				We may also use your data, or permit selected third parties
				(including but not limited to publishers of magazines or other
				publications which you purchase through our Site) to use your data
				(excluding your credit card details), to provide you with
				information about goods and services which may be of interest to you
				and we or they may contact you about these by post or telephone,
				where you have consented for such purposes.<br> <br> If you are an
				existing customer, we will only contact you by electronic means
				(e-mail or SMS) with information about goods and services similar to
				those which were the subject of a previous sale to you.<br> <br> If
				you are a new customer, and where we permit selected third parties
				to use your data, we (or they) will contact you by electronic means
				only if you have consented to this.<br> <br> If you consent to our
				use of your data in this way, or to us passing your details on to
				third parties for marketing purposes, please tick the relevant boxes
				situated on the form on which we collect your data (the registration
				form).<br>
			</p>
			<h3>DISCLOSURE OF YOUR INFORMATION</h3>
			<p>
				We may disclose your personal information to any member of our
				group, which means our subsidiaries, our ultimate holding company
				and its subsidiaries, as defined in section 1159 of the UK Companies
				Act 2006.<br> <br> We may disclose your personal information to
				third parties:<br> <br> In the event that we sell or buy any
				business or assets, in which case we may disclose your personal data
				to the prospective seller or buyer of such business or assets.<br> <br>
				If SK United Limited or substantially all of its assets are acquired
				by a third party, in which case personal data held by it about its
				customers will be one of the transferred assets.<br> <br> If we are
				under a duty to disclose or share your personal data in order to
				comply with any legal obligation (including any relevant court
				order), or in order to enforce our Terms of Use and other
				agreements; or to protect the rights, property, or safety of SK
				United Limited our customers, or others. This includes exchanging
				information with other companies and organisations for the purposes
				of fraud protection and credit risk reduction.<br> <br> Disclosure
				of anonymous information<br> <br> We reserve the right to use and
				dis0 close anonymous information to third parties (such as
				publishers, partners or other interested parties) for internal
				research purposes and profiling.<br>
			</p>
			<h3>YOUR RIGHTS</h3>
			<p>
				You have the right to ask us not to process your personal data for
				marketing purposes. We will usually inform you (before collecting
				your data) if we intend to use your data for such purposes or if we
				intend to disclose your information to any third party for such
				purposes. You can exercise your right to prevent such processing by
				checking certain boxes on the forms we use to collect your data and
				you can alter your instructions to us in the same way. You can also
				exercise the right at any time by contacting us at
				contact@appxpert.co.uk.<br> <br> Our Site may, from time to time,
				contain links to and from the websites of our partner networks,
				advertisers and affiliates. If you follow a link to any of these
				websites, please note that these websites have their own privacy
				policies and that we do not accept any responsibility or liability
				for these policies. Please check these policies before you submit
				any personal data to these websites.<br>
			</p>
			<h3>ACCESS TO INFORMATION</h3>
			<p>
				The Act gives you the right to access certain information held about
				you. Your right of access can be exercised in accordance with the
				Act. Any access request may be subject to a fee of ¬£10 to meet our
				costs in providing you with details of the information we hold about
				you.<br>
			</p>
			<h3>CHANGES TO OUR PRIVACY POLICY</h3>
			<p>
				Any changes we may make to our privacy policy in the future will be
				posted on this page and, where appropriate, notified to you by
				e-mail.<br>
			</p>
			<h3>CONTACT</h3>
			<p>
				Questions, comments and requests regarding this privacy policy are
				welcomed and should be addressed to contact@appxpert.co.uk.<br>
			</p>
		</div>
	</div>
</div>
