<div class="withdrawn">

	<div class="title container dark">
		<h1 class="h1">
			<span class="separator"><span class="hr"></span></span> <span class="text ico"><?php echo(_('My earnings'));?>
			</span> <span class="separator"><span class="hr"></span></span>
		</h1>
	</div>

	<div class="container">
	    <p>Once you have a minimum of £10, you can cash your earnings via Paypal.</p>
	</div>
</div>
