<div class="row">
    <div class="col-xs-12 hidden-xs">
        <div class="panel panel-default left-contigue">
                <img class="img-responsive"
                     src='<?php $this->baseUrl(); ?>/web/themes/default/img/analytics_home.png' />
        </div>
    </div>
</div>

<div class="row">

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">RUNNING A PERFORMANCE CAMPAIGN ON MOBILE</h3>
            </div>

            <div class="row panel-body">
                <div class="col-xs-3">
                    <img class="img-responsive"
                         src='<?php $this->baseUrl(); ?>/web/themes/default/img/analytics_graph.png' />
                </div>

                <div class="col-xs-9 equalheight">

                    <p>BBFA measures what network is performing the best and easily
                        integrates with the main third party tracking solutions, to really
                        understand what is going on after the click.</p>
                    <a href="<?php echo($this->url(array('module' => 'Backoffice', 'controller' => 'login', 'action' => 'index'))); ?>" class="btn btn-lg btn-default bottom">Get started</a>
                </div>

            </div>

        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">RUNNING A BRAND COMPAIGN ON MOBILE ?</h3>
            </div>


            <div class="panel-body">
                <div class="col-xs-3">
                    <img class="img-responsive"
                         src='<?php $this->baseUrl(); ?>/web/themes/default/img/branding_icon.png' />

                </div>
                <div class="col-xs-9 equalheight">
                    <p>
                        BBFA hosts your rich media assets and give you information you
                        would not have from your partners. <br> BBFA knows if your ads are
                        seen or not, and gives you the real reach of your campaign.
                    </p>
                    <a href="<?php echo($this->url(array('module' => 'Backoffice', 'controller' => 'login', 'action' => 'index'))); ?>" class="btn btn-lg btn-default bottom">Get started</a>

                </div>
            </div>
        </div>

    </div>