<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <?php
        $this->headTitle()->setSeparator(' - ');
        $this->headTitle()->prepend(_('NeighbApp'));
        echo $this->headTitle();
        ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" media="screen"
     href="http://tarruda.github.com/bootstrap-datetimepicker/assets/css/bootstrap-datetimepicker.min.css">
        <link rel="icon" type="image/png" href="<?php echo($this->config->themeurl); ?>/favicon.png" />
        <link href="/assets/css/style.css" rel="stylesheet" media="screen">
        <link href="/assets/css/style_1.css" rel="stylesheet" media="screen">

        <link href="/assets/css/neighbapp.css" rel="stylesheet" media="screen">
        <link href="/assets/css/simplePagination.css" rel="stylesheet" media="screen">

        <?php print $this->headLink(); ?>
        <script src="/assets/js/lib/require.js"></script>
        <script src="/assets/js/app.js"></script>
    </head>

    <body>

        <?php if (!$this->hiddehead): ?>
            <?php print $this->Navbar(); ?>
            <?php print $this->Pagetitle(); ?>
        <?php endif; ?>
        <div class="container"><div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <a href="#" class="btn btn-danger danger">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
            <?php print $this->layout()->content; ?>
        </div>
    </body>
</html>