<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <?php
        $this->headTitle()->setSeparator(' - ');
        $this->headTitle()->prepend(_('NeighbApp'));
        echo $this->headTitle();
        ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="icon" type="image/png" href="<?php echo($this->config->themeurl); ?>/favicon.png" />
        <link href="/assets/css/style.css" rel="stylesheet" media="screen">
        <link href="/assets/css/neighbapp.css" rel="stylesheet" media="screen">

<?php print $this->headLink(); ?>
        <script src="/web/js/lib/require.js"></script>
        <script src="/web/js/app.js"></script>
    </head>

    <body>

        <?php if (!$this->hiddehead): ?>
            <?php print $this->Navbar(); ?>
            <?php print $this->Pagetitle(); ?>
            <?php endif; ?>
        <div class="container">
            <?php //print $this->Topbar(); ?>
            <?php echo ( $this->displayFlashMessage() ); ?>
<?php print $this->layout()->content; ?>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/bootswatch.js"></script>
    <script type="text/javascript">
        /* <![CDATA[ */
        (function(){try{var s,a,i,j,r,c,l=document.getElementsByTagName("a"),t=document.createElement("textarea");for(i=0;l.length-i;i++){try{a=l[i].getAttribute("href");if(a&&"www.cloudflare.com/email-protection"==a.substr(7 ,35)){s='';j=43;r=parseInt(a.substr(j,2),16);for(j+=2;a.length-j&&a.substr(j,1)!='X';j+=2){c=parseInt(a.substr(j,2),16)^r;s+=String.fromCharCode(c);}j+=1;s+=a.substr(j,a.length-j);t.innerHTML=s.replace(/</g,"&lt;").replace(/>/g,"&gt;");l[i].setAttribute("href","mailto:"+t.value);}}catch(e){}}}catch(e){}})();
        /* ]]> */
    </script>
</body>
</html>