<!DOCTYPE html>
<html>
    <head>
        <?php print $this->headTitle(); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Main CSS -->
        <link href="/assets/css/style.css" rel="stylesheet" media="screen">
        <link href="/assets/css/neighbapp.css" rel="stylesheet" media="screen">
    </head>

    <body>
        <div class="container" style="padding:10%">
            <div class="bs-component">
                <div class="jumbotron">
                    <div class="row">
                        <div class="col-lg-12">
                            
                            <div class="well bs-component">
                    <?php print $this->layout()->content; ?>
                                </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </body>
</html>