<!DOCTYPE html>
<html>
    <head>
        <?php print $this->headTitle(); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Main CSS -->
        <link href="/assets/css/style.css" rel="stylesheet" media="screen">
        <link href="/assets/css/neighbapp.css" rel="stylesheet" media="screen">
    </head>

    <body>
        <div class="jumbotron">            
            <div id="login">
                <?php print $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>