<!DOCTYPE html>
<html>
    <head>
        <?php print $this->headTitle(); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Main CSS -->
        <link href="/assets/css/style.css" rel="stylesheet" media="screen">
        <link href="/assets/css/neighbapp.css" rel="stylesheet" media="screen">
    </head>

    <body>
        <div class="container" style="padding:10%">
            <div class="bs-component">
                <div class="jumbotron">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="well bs-component">
                                <form class="form-horizontal">
                                    <fieldset>
                                        <legend>Authentification</legend>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="inputEmail">Email</label>
                                            <div class="col-lg-10">
                                                <input type="text" placeholder="Email" id="inputEmail" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="inputPassword">Password</label>
                                            <div class="col-lg-10">
                                                <input type="password" placeholder="Password" id="inputPassword" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-lg-10 col-lg-offset-2">
                                                <button class="btn btn-primary" type="submit">Submit</button>
                                            </div>
                                        </div>
                                    </fieldset>
                                </form>
                                <div class="btn btn-primary btn-xs" id="source-button" style="display: none;">&lt; &gt;</div></div>
                        </div>
                    </div>


                    <?php //print $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </body>
</html>