<html>
<head>
	<title>Web Service Serveur</title>
	<link rel="stylesheet" href="/Services/Soap/Css/doc.css" type="text/css">
</head>
<body>

<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr> <td class="b-box-top-left"></td> <td class="b-box-top-middle"></td> <td class="b-box-top-right"></td> </tr>
<tr><td class="b-box-middle-left"></td><td>

<div id="center-rnd-bar"></div><div id="left-rnd-bar"></div><div id="rigth-rnd-bar"></div>
<div id="main">
<div id="mainpadded">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td>
    <ul>
    <?php foreach ($this->services as $service => $urls):?>
    	<li><?php echo $service;?></li>
    	<ul>
        <?php foreach ($urls as $name => $url):?>
            <?php if(is_array($url)):?>
    			<li><?php echo $name;?></li>
    			<ul>
            	    <?php foreach($url as $subName => $subUrl):?>
    				<li><a href="<?php echo $subUrl;?>"><?php echo $subName;?></a></li>
                    <?php endforeach;?>
    			</ul>
            <?php else:?>
    			<li><a href="<?php echo $url;?>"><?php echo $name;?></a></li>
            <?php endif;?>
        <?php endforeach;?>
    	</ul>
    	<?php endforeach;?>
    </ul>
</td>
</tr>
</table>
</div><div class="footer">WEB SERVICE - sk</div>
</div>
</td><td class="b-box-middle-right"></td> </tr>
<tr> <td class="b-box-bottom-left"></td> <td class="b-box-bottom-middle"></td> <td class="b-box-bottom-right"></td> </tr>
</table>
</body>
</html>