<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h2 class="panel-title"><?php print(_('Add User')) ?></h2>
            </div>
            <div class="panel-body">
                <?php print($this->form); ?>
                <a class="btn btn-default" href="<?php print($this->url(array('module' => 'Backoffice', 'controller' => 'user', 'action' => 'index'), null, true)); ?>">
                    <i class="icon-chevron-left"></i>
                    <?php print(_('annuler')); ?></a>
            </div>
        </div>
    </div>
</div>

