<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h2 class="panel-title"><?php print(_('Delete device')) ?></h2>
            </div>
            <div class="panel-body">
                <p>Confirme ?</p>
                <form method="post" action="/push/devicedelete" class="form-inline" enctype="application/x-www-form-urlencoded">
                    <input type="hidden" id="id" class="form-control col-sm-3" value="<?= $this->id; ?>" name="id">
                    <div class=" form-group ">
                        <input type="submit" placeholder="Yes" icon="ok" buttontype="success" class="btn btn-default" buttons="danger info primary success warning inverse link" value="Yes" id="valide" name="valide"></div>
                    <div class=" form-group ">
                        <input type="submit" placeholder="no" class="btn btn-default" buttons="danger info primary success warning inverse link" value="no" id="unvalide" name="unvalide"></div></form>
            </div>
        </div>
    </div>
</div>