<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h2 class="panel-title"><?php print(_('Push All')) ?></h2>
            </div>
            <div class="panel-body">	

                <form method="post" action="" class="form-horizontal" enctype="application/x-www-form-urlencoded" id="push">
                    <div class=" form-group "><label class="col-sm-2 control-label required" for="data-version_id">Version</label>
                        <div class="col-sm-5">
                            <select required="" class="form-control col-sm-3" id="data-version_id" name="data[version_id]">
                                <?php foreach ($this->versions as $version) : ?>
                                    <option  label="<?= $version['name'] ?>" value="<?= $version['id'] ?>"><?= $version['name'] ?></option>
                                <?php endforeach; ?>
                            </select></div></div>
                    <div class=" form-group "><label class="col-sm-2 control-label required" for="data-message">Message</label>
                        <div class="col-sm-5">
                            <textarea rows="3" required="" class="form-control col-sm-3" id="data-message" name="data[message]"></textarea></div></div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label required" for="data-version_id">Start time</label>
                        <div class='col-sm-5 input-group date' id='datetimepicker1'>
                            <input id="data-start_time" name="data[start_time]" type='text' class="form-control" />
                            <span  class="input-group-addon"><span class="icon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    <div class=" form-group "><div class="col-sm-offset-2 col-sm-3">
                            <input type="submit" class="btn btn-default" buttons="danger info primary success warning inverse link" value="submit" id="data-submit" name="data[submit]"></div></div>
                </form>

                <a class="btn btn-default" href="<?php print($this->url(array('module' => 'Backoffice', 'controller' => 'push', 'action' => 'index'), null, true)); ?>">
                    <i class="icon-chevron-left"></i>
                    <?php print(_('annuler')); ?></a>
            </div>
        </div>
    </div>
</div>

<script>
    requirejs(['main','moment', 'bootstrap-datetimepicker'], function() {
    
        $(function () {
            $('#datetimepicker1').datetimepicker();
        });
    });
</script>