<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h2 class="panel-title"><?php print(_('Update User')) ?></h2>
            </div>
            <div class="panel-body">	
                
                    <div class="form-group">
                    <label class="col-sm-2 control-label required" for="version">Version</label>
                    <div class="col-sm-3">
                        <select required="" class="form-control col-sm-3" id="data-version" name="data[version]">
                            <?php foreach($this->versions as $version) : ?>
                                <?php $selected = ($version['id'] == $this->data['version_id'])?'selected="selected"':"";?>
                                <option  <?= $selected ?>s label="<?= $version['name']?>" value="<?= $version['name']?>"><?= $version['name']?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                  </div>
                
                <?php print($this->form); ?>
                <a class="btn btn-default" href="<?php print($this->url(array('module' => 'Backoffice', 'controller' => 'user', 'action' => 'index'), null, true)); ?>">
                    <i class="icon-chevron-left"></i>
                    <?php print(_('annuler')); ?></a>
            </div>
        </div>
    </div>
</div>
